#==========================================================
#= Configurazione Articoli Web Service - Versione Produzione
#==========================================================
spring:
#==========================================================
#= PARAMETRI DBMS POSTGRESQL 
#==========================================================
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    password: 123_Stella
    url: jdbc:postgresql://postgres-db:5432/AlphaShop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
# ==============================================================
# = Actuator Parameters
# ==============================================================
management:
  info:
    env:
      enabled: true
    git:
      enabled: true
      mode: full
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED
  endpoints:
    web:
      exposure:
        include: health,info,metrics,customInfo
# ==============================================================
# = Actuator Info
# ==============================================================
info:
  assistenza:
    nome: "Nicola La Rocca"
    mail: "nicola_larocca@xantrix.it"
    telefono: "33412345678"
    orario: "9-20"
  nome:
    nome-app: "Articoli Web Service - Autenticazione OAUTH2 keycloak"
# ==============================================================
# = Proprietà Livello Log
# = Default ERROR, WARN e INFO 
# = Levels: TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
# ============================================================== 
logging:
  file:
    name: './logs/ArtSrv.log' #file inserito nella cartella logs 
    max-size: 1MB
    #path: "/logs"
  pattern:
    file: "%d{ dd-MM-yyyy } [%thread] %-5level %logger{36} - %msg%n"
    #console: "%d{dd-MM-yyyy HH:mm:ss} - %msg%n"
    
  # Livello del Log generale (default INFO)
  level:
   root: INFO
  # Livello di log specifico
   org:
    springframework:
     security: DEBUG
     web: INFO
    hibernate: INFO 
   com:
    xantrix:
     webapp:
      controller: INFO
      feign:
       PriceClient: DEBUG
    
# ==============================================================
# = Parametri OpenFeign
# ============================================================== 
feign:
  compression:
    request:
      enabled: true
      mime-types:
      - text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
  client:
    config:
      PriceArtService:
        connect-timeout: 20000
        read-timeout: 20000
      default:
        connect-timeout: 20000
        read-timeout: 20000
